import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link"; 
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* 👇 add bg + full height so no white shows */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-emerald-50 min-h-screen`}>
        {/* header uses same bg, so there's no color seam */}
        <header className="border-b border-emerald-200 bg-emerald-50">
          <nav className="mx-auto flex max-w-6xl items-center gap-6 p-4">
            <Link href="/" className="font-semibold hover:underline">Insights</Link>
            <Link href="/ml-planner" className="text-sm text-zinc-700 hover:underline">ML Planner</Link>
          </nav>
        </header>

        {/* keep padding here minimal so content controls spacing */}
        <main className="mx-auto max-w-6xl p-4 md:p-6">{children}</main>
      </body>
    </html>
  );
}
